version: "3"
services:
  postgres:
    container_name: takemyfarm-postgres
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    container_name: takemyfarm-minio
    image: minio/minio:RELEASE.2022-01-04T07-41-07Z.fips
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      CONSOLE_ACCESS_KEY: minio
      CONSOLE_SECRET_KEY: minio123
      # Debugging
      # MINIO_HTTP_TRACE: /dev/stdout
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

volumes:
  postgres-data:
  minio-data: